#!/bin/bash 

# Allows the first two arguments -dir filename to change the working directory
# Mostly inteded to be used by autograder
if [ "$1" = "-dir" ]; then
   cd $2 
   shift
   shift
fi

# Workaround that looks for the JSON lib in a nearby parent directory
if [ -e "../JSON/json-lib.cm" ]; then
   JSON_LIB='../JSON/json-lib.cm'
elif [ -e "../../JSON/json-lib.cm" ]; then
   JSON_LIB='../../JSON/json-lib.cm'
elif [ -e "../../../JSON/json-lib.cm" ]; then
   JSON_LIB='../../../JSON/json-lib.cm'
else
   JSON_LIB='$/json-lib.cm'
fi

echo "val () = OS.Process.exit (Grade.selfTestCompiler \"$@\\n\");" | sml -Cbasic.print-warnings=false -Cprint.signatures=0 -Ccm.verbose=false -Cparser.primary-prompt='' -m $JSON_LIB ../grader/driver.sml
